# Generated by Django 3.2 on 2023-03-21 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('PostAmount', models.IntegerField(default=0)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moon.avatar')),
                ('gif', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='moon.gif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('disLikes', models.IntegerField(default=0)),
                ('youTube', models.CharField(blank=True, max_length=255, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='static/files')),
                ('fistImage', models.ImageField(blank=True, null=True, upload_to='static/postImgs')),
                ('secondImage', models.ImageField(blank=True, null=True, upload_to='static/postImgs')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
