# Generated by Django 3.2 on 2023-03-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0002_post_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moon.gif'),
        ),
    ]
