# Generated by Django 3.2 on 2023-03-23 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0004_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.season'),
        ),
    ]
