# Generated by Django 3.2 on 2023-03-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0005_post_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='createDate',
            field=models.DateField(null=True),
        ),
    ]
