# Generated by Django 3.2 on 2023-04-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0008_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disLikes',
            new_name='dislikes',
        ),
    ]
