# Generated by Django 3.2 on 2023-04-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0014_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
    ]
