# Generated by Django 3.2 on 2023-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0016_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
