# Generated by Django 3.2 on 2023-04-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0017_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
