# Generated by Django 3.2 on 2023-04-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0019_tag_taglink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fistImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.firstimg'),
        ),
    ]
