# Generated by Django 3.2 on 2023-04-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0020_alter_post_fistimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.pdf'),
        ),
        migrations.AlterField(
            model_name='post',
            name='secondImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.secondimg'),
        ),
    ]
