# Generated by Django 3.2 on 2023-04-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0022_auto_20230417_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='feild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='feild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.feild'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='feild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moon.feild'),
        ),
    ]
