# Generated by Django 3.2 on 2023-04-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moon', '0023_auto_20230418_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
